// Auto-generated by rnwind — do not edit by hand.
// Overwritten on Metro start / theme CSS change.

declare module 'react-native' {
  interface ViewProps { className?: string }
  interface TextProps { className?: string }
  interface ImageProps { className?: string }
  interface ImageBackgroundProps { className?: string }
  interface ScrollViewProps { className?: string; contentContainerClassName?: string }
  interface PressableProps { className?: string }
  interface ModalProps { className?: string }
  interface TextInputProps { className?: string }
  interface TouchableOpacityProps { className?: string }
  interface TouchableHighlightProps { className?: string }
  interface TouchableNativeFeedbackProps { className?: string }
  interface TouchableWithoutFeedbackProps { className?: string }
  interface SafeAreaViewProps { className?: string }
  interface KeyboardAvoidingViewProps { className?: string }
  interface RefreshControlProps { className?: string }
  interface StatusBarProps { className?: string }
  interface SwitchProps { className?: string }
  interface ActivityIndicatorProps { className?: string }
  interface SectionListProps { className?: string; contentContainerClassName?: string }
  interface FlatListProps<ItemT> { className?: string; contentContainerClassName?: string }
  interface VirtualizedListProps<ItemT> { className?: string; contentContainerClassName?: string }
}

declare module 'rnwind' {
  export interface RnwindConfig {
    themes: readonly ['light', 'dark']
  }
}

export {}
