import { mkdirSync, writeFileSync } from 'node:fs'
import path from 'node:path'

/**
 * React Native component-props interfaces rnwind augments. Adding an
 * optional `className?: string` to each lets TypeScript accept
 * `<View className="…" />` without the user touching types by hand.
 * The generic ones are written with a placeholder so the output type
 * stays parameterised.
 */
const INTERFACES: ReadonlyArray<string | { name: string; generic: string }> = [
  'ViewProps',
  'TextProps',
  'ImageProps',
  'ImageBackgroundProps',
  'ScrollViewProps',
  'PressableProps',
  'ModalProps',
  'TextInputProps',
  'TouchableOpacityProps',
  'TouchableHighlightProps',
  'TouchableNativeFeedbackProps',
  'TouchableWithoutFeedbackProps',
  'SafeAreaViewProps',
  'KeyboardAvoidingViewProps',
  'RefreshControlProps',
  'StatusBarProps',
  'SwitchProps',
  'ActivityIndicatorProps',
  'SectionListProps',
  { name: 'FlatListProps', generic: 'ItemT' },
  { name: 'VirtualizedListProps', generic: 'ItemT' },
]

/**
 * Built-in prefix wired into every install. Restricted to the interfaces
 * that natively expose `contentContainerStyle` so TypeScript doesn't
 * start accepting `<View contentContainerClassName="…" />` — RN would
 * silently ignore it at runtime and a typed lint is more useful than a
 * permissive one. User prefixes don't come with this restriction; rnwind
 * can't know which component props they target.
 */
const BUILTIN_PREFIX = 'contentContainer'

/**
 * Interfaces that expose `contentContainerStyle` in React Native's own
 * types — the set the built-in prefix's `.d.ts` augmentation targets.
 * Everything else stays `className`-only by default.
 */
const CONTENT_CONTAINER_INTERFACES: ReadonlySet<string> = new Set([
  'ScrollViewProps',
  'FlatListProps',
  'SectionListProps',
  'VirtualizedListProps',
])

/**
 * Build the body of one interface augmentation: `className?: string`
 * plus `<prefix>ClassName?: string` for every prefix that applies to
 * THIS interface. Emits a single-line body so the file stays easy to
 * scan and diff.
 * @param interfaceName Bare interface name (generic parameters stripped).
 * @param userPrefixes Extra prefixes from the Metro config — applied to
 *   every interface the same way `className` is.
 * @returns Space-separated property declarations.
 */
function buildInterfaceBody(interfaceName: string, userPrefixes: readonly string[]): string {
  const props = ['className?: string']
  if (CONTENT_CONTAINER_INTERFACES.has(interfaceName)) props.push(`${BUILTIN_PREFIX}ClassName?: string`)
  for (const prefix of userPrefixes) {
    if (prefix === BUILTIN_PREFIX) continue
    props.push(`${prefix}ClassName?: string`)
  }
  return props.join('; ')
}

/**
 * Write the rnwind TypeScript declaration file. The generated `.d.ts`
 * declares a `rnwind` module augmentation for `react-native`'s
 * component props — every interface gets an optional `className?:
 * string` plus `<prefix>ClassName?: string` for each active prefix.
 * Runtime-rendered schemes (`@variant` blocks) are reflected in the
 * `Scheme` union so `useScheme()` returns the actual names.
 *
 * Called once at Metro-config time — overwrite-on-rewrite so the file
 * stays in sync with the user's current theme CSS + prefix config.
 * @param targetPath Absolute path to write (typically `rnwind-types.d.ts` at project root).
 * @param schemes Scheme names from the user's `@variant` blocks (empty when none declared).
 * @param classNamePrefixes Extra prefixes from the Metro config — merged
 *   on top of the built-in `'contentContainer'`. Defaults to empty.
 */
export function writeDtsFile(
  targetPath: string,
  schemes: readonly string[],
  classNamePrefixes: readonly string[] = [],
): void {
  const lines: string[] = [
    '// Auto-generated by rnwind — do not edit by hand.',
    '// Overwritten on Metro start / theme CSS change.',
    '',
    `declare module 'react-native' {`,
  ]
  for (const entry of INTERFACES) {
    const name = typeof entry === 'string' ? entry : entry.name
    const body = buildInterfaceBody(name, classNamePrefixes)
    if (typeof entry === 'string') {
      lines.push(`  interface ${entry} { ${body} }`)
      continue
    }
    lines.push(`  interface ${entry.name}<${entry.generic}> { ${body} }`)
  }
  lines.push('}', '')
  if (schemes.length > 0) {
    lines.push(`declare module 'rnwind' {`, `  export interface RnwindConfig {`)
    const schemeLiterals = schemes.map((s) => `'${s}'`).join(', ')
    lines.push(`    themes: readonly [${schemeLiterals}]`, `  }`, '}', '')
  }
  // The `export {}` is mandatory — without at least one top-level
  // import/export, TypeScript treats this file as a SCRIPT and the
  // `declare module 'react-native'` block above becomes a complete
  // *replacement* declaration (hiding the real RN exports like
  // `Pressable`, `useColorScheme`, etc.). With `export {}` the file
  // becomes a module and the `declare module` blocks are interpreted as
  // *augmentations* — which is what we want.
  lines.push('export {}', '')
  mkdirSync(path.dirname(targetPath), { recursive: true })
  writeFileSync(targetPath, lines.join('\n'), 'utf8')
}
